-- ============================================================
--  GAMIFICA — Biblioteca de Caça-palavras (Fundamental I)
--  40 jogos: 5 anos (1º a 5º) x 8 disciplinas, cada palavra com dica.
--  Idempotente: pode ser importado mais de uma vez sem duplicar.
--  Requer o professor demo (Ana Souza). Se não existir, ajuste o e-mail abaixo.
-- ============================================================
SET NAMES utf8mb4;

-- Professor e escola de referência (professor demo)
SET @prof := (SELECT id FROM usuarios WHERE email = 'ana@escola.edu.br' LIMIT 1);
SET @esc  := (SELECT escola_id FROM usuarios WHERE id = @prof LIMIT 1);

-- Turmas 1º a 5º Ano (cria se não existirem)
INSERT INTO turmas (escola_id, nome, ano_letivo) SELECT @esc, '1º Ano', YEAR(CURDATE()) FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM turmas WHERE escola_id = @esc AND nome = '1º Ano');
INSERT INTO turmas (escola_id, nome, ano_letivo) SELECT @esc, '2º Ano', YEAR(CURDATE()) FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM turmas WHERE escola_id = @esc AND nome = '2º Ano');
INSERT INTO turmas (escola_id, nome, ano_letivo) SELECT @esc, '3º Ano', YEAR(CURDATE()) FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM turmas WHERE escola_id = @esc AND nome = '3º Ano');
INSERT INTO turmas (escola_id, nome, ano_letivo) SELECT @esc, '4º Ano', YEAR(CURDATE()) FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM turmas WHERE escola_id = @esc AND nome = '4º Ano');
INSERT INTO turmas (escola_id, nome, ano_letivo) SELECT @esc, '5º Ano', YEAR(CURDATE()) FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM turmas WHERE escola_id = @esc AND nome = '5º Ano');

-- ═══════════════ 1º Ano ═══════════════
SET @turma := (SELECT id FROM turmas WHERE escola_id = @esc AND nome = '1º Ano' LIMIT 1);
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Matemática' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Matemática');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Português' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Português');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Inglês' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Inglês');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Educação Física' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Educação Física');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Ciências' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Ciências');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Artes' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Artes');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Geografia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Geografia');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'História' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='História');
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '➗ Caça-palavras de Matemática · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Matemática', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "TRES", "d": "Quantas rodas tem um triciclo? 🚲"}, {"p": "QUATRO", "d": "Número de patas de um cachorro 🐕"}, {"p": "CINCO", "d": "Quantos dedos tem uma mão? ✋"}, {"p": "SEIS", "d": "A metade de uma dúzia (12 dividido por 2)"}, {"p": "ZERO", "d": "Número que quer dizer \'nenhum\': 0"}, {"p": "BOLA", "d": "Brinquedo redondo que rola e quica ⚽"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📚 Caça-palavras de Português · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Português', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "VOGAL", "d": "A, E, I, O e U são as letras chamadas de ___"}, {"p": "LETRA", "d": "Cada sinalzinho do alfabeto: A, B, C..."}, {"p": "GATO", "d": "Bichinho de estimação que faz \'miau\' 🐱"}, {"p": "BOLO", "d": "Doce gostoso que tem no aniversário 🎂"}, {"p": "CASA", "d": "Lugar onde a gente mora 🏠"}, {"p": "PATO", "d": "Ave que faz \'quá-quá\' e adora nadar 🦆"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔤 Caça-palavras de Inglês · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Inglês', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "CAT", "d": "\'Gato\' em inglês 🐱"}, {"p": "DOG", "d": "\'Cachorro\' em inglês 🐶"}, {"p": "RED", "d": "A cor \'vermelho\' em inglês 🔴"}, {"p": "BLUE", "d": "A cor \'azul\' em inglês 🔵"}, {"p": "SUN", "d": "O \'sol\' em inglês ☀️"}, {"p": "BOOK", "d": "\'Livro\' em inglês 📖"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '⚽ Caça-palavras de Educação Física · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Educação Física', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "PULAR", "d": "O que fazemos com a corda, dando saltinhos"}, {"p": "CORRER", "d": "Mover-se bem rápido com as pernas 🏃"}, {"p": "BOLA", "d": "Usada no futebol e no basquete ⚽"}, {"p": "NADAR", "d": "Mover o corpo dentro da água 🏊"}, {"p": "PIQUE", "d": "Brincadeira de pega-pega: pique-___"}, {"p": "DANCAR", "d": "Mexer o corpo no ritmo da música 💃"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔬 Caça-palavras de Ciências · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Ciências', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "SOL", "d": "Estrela que ilumina e aquece o dia ☀️"}, {"p": "AGUA", "d": "Bebemos quando estamos com sede 💧"}, {"p": "FLOR", "d": "Parte colorida e cheirosa da planta 🌸"}, {"p": "ARVORE", "d": "Planta grande, com tronco e folhas 🌳"}, {"p": "PEIXE", "d": "Animal que vive na água e tem escamas 🐟"}, {"p": "MICO", "d": "Macaquinho pequeno que pula nas árvores 🐒"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🎨 Caça-palavras de Artes · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Artes', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "COR", "d": "Azul, vermelho e amarelo são tipos de ___ 🎨"}, {"p": "LAPIS", "d": "Usamos para desenhar e escrever ✏️"}, {"p": "TINTA", "d": "Líquido colorido que usamos para pintar"}, {"p": "PINCEL", "d": "Ferramenta de cerdas para passar tinta 🖌️"}, {"p": "AZUL", "d": "A cor do céu num dia bonito 💙"}, {"p": "PAPEL", "d": "Onde desenhamos e escrevemos 📄"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🌍 Caça-palavras de Geografia · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Geografia', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "RUA", "d": "Caminho por onde passam carros e pessoas"}, {"p": "ESCOLA", "d": "Lugar onde estudamos e brincamos 🏫"}, {"p": "CIDADE", "d": "Lugar cheio de casas, ruas e prédios 🏙️"}, {"p": "MAPA", "d": "Desenho que mostra onde ficam os lugares 🗺️"}, {"p": "CAMPO", "d": "Lugar do interior, com muito verde 🌾"}, {"p": "PRAIA", "d": "Lugar com areia e mar 🏖️"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📜 Caça-palavras de História · 1º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'História', 60, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 1º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 1º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "FAMILIA", "d": "Papai, mamãe, irmãos e você 👨‍👩‍👧"}, {"p": "ONTEM", "d": "O dia que passou, antes de hoje"}, {"p": "HOJE", "d": "O dia de agora, em que estamos"}, {"p": "VOVO", "d": "O pai do seu pai ou da sua mãe 👴"}, {"p": "NOME", "d": "Como cada pessoa é chamada"}, {"p": "FESTA", "d": "Comemoração com bolo, música e alegria 🎉"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);

-- ═══════════════ 2º Ano ═══════════════
SET @turma := (SELECT id FROM turmas WHERE escola_id = @esc AND nome = '2º Ano' LIMIT 1);
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Matemática' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Matemática');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Português' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Português');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Inglês' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Inglês');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Educação Física' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Educação Física');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Ciências' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Ciências');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Artes' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Artes');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Geografia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Geografia');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'História' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='História');
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '➗ Caça-palavras de Matemática · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Matemática', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "DEZ", "d": "Número que vem depois do nove: 10"}, {"p": "DEZENA", "d": "Um grupo de dez unidades"}, {"p": "DOBRO", "d": "O ___ de 4 é 8 (é multiplicar por 2)"}, {"p": "METADE", "d": "A ___ de 10 é 5"}, {"p": "SOMAR", "d": "Juntar quantidades; o mesmo que adicionar"}, {"p": "REGUA", "d": "Serve para medir e traçar linhas retas 📏"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📚 Caça-palavras de Português · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Português', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "SILABA", "d": "Pedacinho da palavra: CA-SA tem duas"}, {"p": "ACENTO", "d": "Sinalzinho sobre a letra, como no \'á\' de café"}, {"p": "PLURAL", "d": "Mais de um; o ___ de gato é gatos"}, {"p": "FRASE", "d": "Conjunto de palavras que tem sentido"}, {"p": "PONTO", "d": "Sinal que encerra a frase: ."}, {"p": "MASCULINO", "d": "Gênero das palavras \'o menino\', \'o cão\'"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔤 Caça-palavras de Inglês · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Inglês', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "GREEN", "d": "A cor \'verde\' em inglês 🟢"}, {"p": "APPLE", "d": "A fruta \'maçã\' em inglês 🍎"}, {"p": "HOUSE", "d": "\'Casa\' em inglês 🏠"}, {"p": "HELLO", "d": "Como se diz \'olá\' em inglês 👋"}, {"p": "WATER", "d": "\'Água\' em inglês 💧"}, {"p": "THREE", "d": "O número \'três\' em inglês"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '⚽ Caça-palavras de Educação Física · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Educação Física', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "FUTEBOL", "d": "Esporte jogado com os pés e uma bola ⚽"}, {"p": "EQUIPE", "d": "Grupo de jogadores do mesmo time"}, {"p": "AMARELINHA", "d": "Brincadeira de pular casas numeradas no chão"}, {"p": "ALONGAR", "d": "Esticar o corpo antes dos exercícios 🤸"}, {"p": "CORRIDA", "d": "Prova de quem chega mais rápido 🏃"}, {"p": "PETECA", "d": "Brinquedo de penas que batemos com a mão"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔬 Caça-palavras de Ciências · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Ciências', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "PLANTA", "d": "Ser vivo que nasce da semente e tem raiz 🌱"}, {"p": "SEMENTE", "d": "Dela nasce uma nova planta"}, {"p": "INSETO", "d": "Animal de seis patas, como a formiga 🐜"}, {"p": "CHUVA", "d": "Água que cai das nuvens 🌧️"}, {"p": "DENTES", "d": "Usamos para mastigar; escovamos todo dia 🦷"}, {"p": "RAIZ", "d": "Parte da planta que fica embaixo da terra"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🎨 Caça-palavras de Artes · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Artes', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "PINTURA", "d": "Obra feita com tinta e pincel 🖼️"}, {"p": "MUSICA", "d": "Arte feita com sons e ritmo 🎵"}, {"p": "TEATRO", "d": "Arte de representar histórias no palco 🎭"}, {"p": "COLAGEM", "d": "Arte de colar papéis para formar figuras ✂️"}, {"p": "CIRCULO", "d": "Forma bem redonda, como a roda ⭕"}, {"p": "VERDE", "d": "Cor que sai da mistura de azul com amarelo 💚"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🌍 Caça-palavras de Geografia · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Geografia', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "BAIRRO", "d": "Parte da cidade onde fica a sua casa"}, {"p": "RIO", "d": "Curso de água doce que corre pela terra 🏞️"}, {"p": "NORTE", "d": "Um dos pontos do mapa (o oposto do sul)"}, {"p": "PLACA", "d": "Sinal na rua que informa e orienta 🚸"}, {"p": "PONTE", "d": "Passagem construída por cima de um rio 🌉"}, {"p": "HORTA", "d": "Lugar onde se plantam verduras e legumes 🥕"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📜 Caça-palavras de História · 2º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'História', 70, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 2º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 2º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "PASSADO", "d": "O tempo que já aconteceu, antes de hoje"}, {"p": "CALENDARIO", "d": "Mostra os dias, semanas e meses 📅"}, {"p": "ANTIGO", "d": "Muito velho, de muito tempo atrás"}, {"p": "SEMANA", "d": "Período de sete dias seguidos"}, {"p": "MEMORIA", "d": "Onde guardamos nossas lembranças 🧠"}, {"p": "BRINQUEDO", "d": "Antigamente eram de madeira; hoje há muitos"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);

-- ═══════════════ 3º Ano ═══════════════
SET @turma := (SELECT id FROM turmas WHERE escola_id = @esc AND nome = '3º Ano' LIMIT 1);
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Matemática' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Matemática');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Português' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Português');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Inglês' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Inglês');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Educação Física' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Educação Física');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Ciências' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Ciências');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Artes' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Artes');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Geografia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Geografia');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'História' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='História');
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '➗ Caça-palavras de Matemática · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Matemática', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "CENTENA", "d": "Um grupo de cem unidades"}, {"p": "DIVIDIR", "d": "Repartir em partes iguais"}, {"p": "TRIANGULO", "d": "Figura que tem três lados 🔺"}, {"p": "QUADRADO", "d": "Figura com quatro lados iguais ⬛"}, {"p": "SUBTRAIR", "d": "Tirar; o mesmo que diminuir"}, {"p": "METRO", "d": "Unidade usada para medir comprimento 📏"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📚 Caça-palavras de Português · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Português', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 13, 13, '[{"p": "SUBSTANTIVO", "d": "Palavra que dá nome às coisas (casa, gato)"}, {"p": "ALFABETO", "d": "Conjunto de todas as letras, de A a Z 🔤"}, {"p": "RIMA", "d": "Sons parecidos no fim dos versos (gato/pato)"}, {"p": "LEITURA", "d": "O ato de ler um texto ou um livro 📖"}, {"p": "DITADO", "d": "Atividade de escrever aquilo que se ouve"}, {"p": "MAIUSCULA", "d": "Letra grande, usada no começo dos nomes"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔤 Caça-palavras de Inglês · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Inglês', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "YELLOW", "d": "A cor \'amarelo\' em inglês 🟡"}, {"p": "SCHOOL", "d": "\'Escola\' em inglês 🏫"}, {"p": "FRIEND", "d": "\'Amigo\' em inglês 🤝"}, {"p": "FAMILY", "d": "\'Família\' em inglês 👨‍👩‍👧"}, {"p": "ORANGE", "d": "A fruta \'laranja\' em inglês 🍊"}, {"p": "TEACHER", "d": "\'Professor\' em inglês 👩‍🏫"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '⚽ Caça-palavras de Educação Física · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Educação Física', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "BASQUETE", "d": "Esporte de arremessar a bola na cesta 🏀"}, {"p": "GINASTICA", "d": "Esporte de saltos, giros e equilíbrio 🤸"}, {"p": "VOLEI", "d": "Esporte com a bola por cima da rede 🏐"}, {"p": "CAPOEIRA", "d": "Arte brasileira que mistura luta e dança"}, {"p": "ARBITRO", "d": "Pessoa que apita e marca as faltas no jogo"}, {"p": "SALTO", "d": "Impulso do corpo para cima ou para a frente"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔬 Caça-palavras de Ciências · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Ciências', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "OXIGENIO", "d": "Gás do ar que respiramos para viver"}, {"p": "VERTEBRADO", "d": "Animal que tem coluna com vértebras"}, {"p": "HABITAT", "d": "Lugar natural onde um animal vive"}, {"p": "PULMAO", "d": "Órgão que usamos para respirar 🫁"}, {"p": "ESQUELETO", "d": "Todos os ossos do corpo juntos 💀"}, {"p": "MAMIFERO", "d": "Animal que mama leite quando é filhote 🐄"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🎨 Caça-palavras de Artes · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Artes', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "PAISAGEM", "d": "Desenho ou pintura de um lugar 🏞️"}, {"p": "ESCULTURA", "d": "Arte feita em barro, pedra ou madeira 🗿"}, {"p": "MELODIA", "d": "Sequência de sons que forma a música 🎶"}, {"p": "RETRATO", "d": "Desenho ou foto do rosto de alguém 🖼️"}, {"p": "MOSAICO", "d": "Figura formada por várias pecinhas coloridas"}, {"p": "PRIMARIA", "d": "Cor ___: azul, vermelho e amarelo"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🌍 Caça-palavras de Geografia · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Geografia', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 10, 10, '[{"p": "ESTADO", "d": "São Paulo e Bahia são exemplos de ___"}, {"p": "CAPITAL", "d": "Cidade principal de um estado ou país"}, {"p": "OCEANO", "d": "Enorme massa de água salgada 🌊"}, {"p": "MONTANHA", "d": "Elevação muito alta do terreno ⛰️"}, {"p": "BUSSOLA", "d": "Instrumento que sempre aponta o norte 🧭"}, {"p": "FLORESTA", "d": "Lugar com muitíssimas árvores juntas 🌳"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📜 Caça-palavras de História · 3º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'História', 80, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 3º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 3º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 10, 10, '[{"p": "INDIGENA", "d": "Foram os primeiros habitantes do Brasil 🏹"}, {"p": "COLONIA", "d": "O Brasil já foi uma ___ de Portugal"}, {"p": "MUSEU", "d": "Lugar que guarda e expõe objetos antigos 🏛️"}, {"p": "CULTURA", "d": "Costumes, festas e danças de um povo"}, {"p": "PORTUGAL", "d": "País da Europa que colonizou o Brasil"}, {"p": "CARAVELA", "d": "Navio antigo usado nas grandes viagens ⛵"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);

-- ═══════════════ 4º Ano ═══════════════
SET @turma := (SELECT id FROM turmas WHERE escola_id = @esc AND nome = '4º Ano' LIMIT 1);
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Matemática' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Matemática');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Português' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Português');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Inglês' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Inglês');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Educação Física' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Educação Física');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Ciências' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Ciências');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Artes' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Artes');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Geografia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Geografia');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'História' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='História');
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '➗ Caça-palavras de Matemática · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Matemática', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "FRACAO", "d": "Uma parte de um inteiro, como 1/2"}, {"p": "PERIMETRO", "d": "A soma de todos os lados de uma figura"}, {"p": "DECIMAL", "d": "Número com vírgula, como 2,5"}, {"p": "ANGULO", "d": "Abertura entre duas linhas que se encontram 📐"}, {"p": "MILHAR", "d": "Um grupo de mil unidades"}, {"p": "SIMETRIA", "d": "Quando os dois lados ficam iguais, como no espelho"}, {"p": "GRAFICO", "d": "Desenho que mostra dados em barras 📊"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📚 Caça-palavras de Português · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Português', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "ADJETIVO", "d": "Palavra que descreve algo (bonito, grande)"}, {"p": "VERBO", "d": "Palavra de ação (correr, pular, ler)"}, {"p": "SINONIMO", "d": "Palavra de sentido igual (feliz e contente)"}, {"p": "ANTONIMO", "d": "Palavra de sentido oposto (alto e baixo)"}, {"p": "NARRATIVA", "d": "Texto que conta uma história 📚"}, {"p": "PARAGRAFO", "d": "Trecho do texto que começa em nova linha"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔤 Caça-palavras de Inglês · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Inglês', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 9, 9, '[{"p": "MONDAY", "d": "\'Segunda-feira\' em inglês 📅"}, {"p": "WINTER", "d": "A estação \'inverno\' em inglês ❄️"}, {"p": "PURPLE", "d": "A cor \'roxo\' em inglês 🟣"}, {"p": "MOTHER", "d": "\'Mãe\' em inglês 👩"}, {"p": "NUMBER", "d": "\'Número\' em inglês 🔢"}, {"p": "SUMMER", "d": "A estação \'verão\' em inglês ☀️"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '⚽ Caça-palavras de Educação Física · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Educação Física', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "HANDEBOL", "d": "Esporte de arremessar a bola com as mãos"}, {"p": "ATLETISMO", "d": "Provas de corrida, salto e arremesso 🏅"}, {"p": "XADREZ", "d": "Jogo de tabuleiro com rei, rainha e peões ♟️"}, {"p": "COOPERAR", "d": "Trabalhar junto com os colegas do time 🤝"}, {"p": "EQUILIBRIO", "d": "Habilidade de não cair, como na trave"}, {"p": "ARREMESSO", "d": "Lançamento da bola em direção ao alvo"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔬 Caça-palavras de Ciências · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Ciências', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "DIGESTAO", "d": "Processo que transforma o alimento no corpo"}, {"p": "MICROBIO", "d": "Ser vivo minúsculo, só visto no microscópio 🔬"}, {"p": "ENERGIA", "d": "O Sol é a nossa maior fonte de ___ ⚡"}, {"p": "RECICLAR", "d": "Transformar o lixo em algo novo e útil ♻️"}, {"p": "NUTRIENTE", "d": "Substância dos alimentos que dá saúde 🥗"}, {"p": "PLANETA", "d": "A Terra é o nosso ___ 🌍"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🎨 Caça-palavras de Artes · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Artes', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 13, 13, '[{"p": "AQUARELA", "d": "Tinta que se mistura e dilui com água 🎨"}, {"p": "SECUNDARIA", "d": "Cor ___: verde, laranja e roxo"}, {"p": "FOTOGRAFIA", "d": "Imagem capturada por uma câmera 📷"}, {"p": "HARMONIA", "d": "Combinação agradável de cores ou sons"}, {"p": "ORIGAMI", "d": "Arte japonesa de dobrar papel 🦢"}, {"p": "PERSPECTIVA", "d": "Técnica que dá profundidade ao desenho"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🌍 Caça-palavras de Geografia · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Geografia', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "RELEVO", "d": "Formas da terra: montanhas, planícies, vales"}, {"p": "CLIMA", "d": "Pode ser quente, frio, chuvoso ou seco 🌦️"}, {"p": "REGIAO", "d": "O Brasil tem cinco: Norte, Sul, Nordeste..."}, {"p": "POPULACAO", "d": "O conjunto de pessoas que vivem num lugar"}, {"p": "FRONTEIRA", "d": "Linha que separa dois países ou estados"}, {"p": "HEMISFERIO", "d": "Cada metade da Terra: Norte ou Sul 🌐"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📜 Caça-palavras de História · 4º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'História', 90, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 4º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 4º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "IMIGRANTE", "d": "Pessoa que veio morar aqui vinda de outro país"}, {"p": "REPUBLICA", "d": "Forma de governo com um presidente eleito"}, {"p": "IMPERIO", "d": "Época em que o Brasil teve um imperador 👑"}, {"p": "BANDEIRA", "d": "Símbolo do país, verde e amarela 🇧🇷"}, {"p": "CIDADANIA", "d": "Direitos e deveres de quem vive em sociedade"}, {"p": "ESCRAVIDAO", "d": "Trabalho forçado de pessoas no passado do Brasil"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);

-- ═══════════════ 5º Ano ═══════════════
SET @turma := (SELECT id FROM turmas WHERE escola_id = @esc AND nome = '5º Ano' LIMIT 1);
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Matemática' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Matemática');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Português' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Português');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Inglês' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Inglês');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Educação Física' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Educação Física');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Ciências' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Ciências');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Artes' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Artes');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'Geografia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='Geografia');
INSERT INTO professor_turma (professor_id, turma_id, disciplina) SELECT @prof, @turma, 'História' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM professor_turma WHERE professor_id=@prof AND turma_id=@turma AND disciplina='História');
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '➗ Caça-palavras de Matemática · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Matemática', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='➗ Caça-palavras de Matemática · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 13, 13, '[{"p": "PORCENTAGEM", "d": "Uma parte em cada cem, como 50%"}, {"p": "POLIGONO", "d": "Figura fechada de vários lados retos"}, {"p": "VOLUME", "d": "O espaço que um objeto ocupa 📦"}, {"p": "DIVISOR", "d": "Número pelo qual se divide outro"}, {"p": "MEDIA", "d": "Soma dos valores dividida pela quantidade"}, {"p": "DIAMETRO", "d": "Linha que corta o círculo passando pelo centro"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📚 Caça-palavras de Português · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Português', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📚 Caça-palavras de Português · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 12, 12, '[{"p": "PRONOME", "d": "Palavra que substitui o nome (ele, ela, nós)"}, {"p": "ORTOGRAFIA", "d": "O modo certo de escrever as palavras ✍️"}, {"p": "ADVERBIO", "d": "Palavra que indica modo, tempo ou lugar"}, {"p": "CONECTIVO", "d": "Palavra que liga ideias (mas, porque, então)"}, {"p": "CRONICA", "d": "Texto curto sobre acontecimentos do dia a dia"}, {"p": "PARLENDA", "d": "Versinho popular de brincar, como \'um, dois, feijão\'"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔤 Caça-palavras de Inglês · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Inglês', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔤 Caça-palavras de Inglês · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 11, 11, '[{"p": "BREAKFAST", "d": "A refeição \'café da manhã\' em inglês 🍳"}, {"p": "WEEKEND", "d": "O \'fim de semana\' em inglês"}, {"p": "WEATHER", "d": "O \'tempo\' (clima) em inglês 🌦️"}, {"p": "COUNTRY", "d": "\'País\' em inglês 🌎"}, {"p": "LIBRARY", "d": "\'Biblioteca\' em inglês 📚"}, {"p": "KITCHEN", "d": "\'Cozinha\' em inglês 🍽️"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '⚽ Caça-palavras de Educação Física · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Educação Física', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='⚽ Caça-palavras de Educação Física · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 15, 15, '[{"p": "FUTSAL", "d": "Futebol de salão, jogado numa quadra"}, {"p": "TATICA", "d": "O plano de jogo para tentar vencer a partida"}, {"p": "OLIMPIADA", "d": "A maior competição esportiva do mundo 🏅"}, {"p": "ADVERSARIO", "d": "O time ou jogador contra quem se disputa"}, {"p": "MODALIDADE", "d": "Cada tipo de esporte (natação, judô, vôlei)"}, {"p": "FLEXIBILIDADE", "d": "Capacidade de dobrar o corpo com facilidade"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🔬 Caça-palavras de Ciências · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Ciências', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🔬 Caça-palavras de Ciências · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 13, 13, '[{"p": "CIRCULACAO", "d": "O caminho que o sangue faz pelo corpo ❤️"}, {"p": "EVAPORACAO", "d": "Passagem da água de líquido para vapor 💨"}, {"p": "ECOSSISTEMA", "d": "Conjunto dos seres vivos e do ambiente 🌳"}, {"p": "RESPIRACAO", "d": "Puxar oxigênio e soltar gás carbônico 🫁"}, {"p": "PUBERDADE", "d": "Fase de mudanças do corpo na adolescência"}, {"p": "GRAVIDADE", "d": "Força que puxa tudo para o chão 🍎"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🎨 Caça-palavras de Artes · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Artes', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🎨 Caça-palavras de Artes · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 14, 14, '[{"p": "ABSTRATO", "d": "Arte sem figuras reais, só formas e cores"}, {"p": "GRAFITE", "d": "Arte urbana feita em muros com spray 🎨"}, {"p": "PARTITURA", "d": "Papel onde se escrevem as notas musicais 🎼"}, {"p": "COREOGRAFIA", "d": "A sequência de passos de uma dança 💃"}, {"p": "CONTRASTE", "d": "Diferença forte entre cores, como claro e escuro"}, {"p": "RENASCIMENTO", "d": "Período de grandes artistas, como Leonardo da Vinci"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '🌍 Caça-palavras de Geografia · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'Geografia', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='🌍 Caça-palavras de Geografia · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 13, 13, '[{"p": "LATITUDE", "d": "Linhas horizontais do mapa, paralelas ao Equador"}, {"p": "URBANO", "d": "Relativo à cidade (o oposto de rural) 🏙️"}, {"p": "MIGRACAO", "d": "Movimento de pessoas de um lugar para outro"}, {"p": "ATMOSFERA", "d": "Camada de ar que envolve toda a Terra"}, {"p": "HIDROGRAFIA", "d": "Estudo dos rios, lagos e mares de uma região 🌊"}, {"p": "COORDENADA", "d": "Par de números que localiza um ponto no mapa"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);
INSERT INTO atividades (professor_id, turma_id, titulo, descricao, tipo, disciplina, xp_recompensa, max_tentativas, publicada) SELECT @prof, @turma, '📜 Caça-palavras de História · 5º Ano', 'Leia cada dica e ache a palavra escondida na grade. Tentativas ilimitadas — só o seu melhor resultado conta!', 'cacapalavras', 'História', 100, 0, 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 5º Ano');
SET @atv := (SELECT id FROM atividades WHERE turma_id=@turma AND titulo='📜 Caça-palavras de História · 5º Ano' LIMIT 1);
INSERT INTO cacapalavras_config (atividade_id, grid_linhas, grid_colunas, palavras, grade_gerada) SELECT @atv, 14, 14, '[{"p": "CIVILIZACAO", "d": "Sociedade organizada, como a egípcia ou a romana"}, {"p": "REVOLUCAO", "d": "Uma grande mudança na sociedade ou no governo"}, {"p": "DEMOCRACIA", "d": "Governo em que o povo escolhe seus líderes 🗳️"}, {"p": "PATRIMONIO", "d": "Bens históricos que devem ser preservados 🏛️"}, {"p": "CONSTITUICAO", "d": "A lei principal que organiza um país 📜"}, {"p": "ABOLICAO", "d": "O fim da escravidão no Brasil, em 1888"}]', NULL FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM cacapalavras_config WHERE atividade_id=@atv);

-- Total: 40 caça-palavras · 241 palavras com dicas.
